const SRI_LANKA_BRANCH_CITIES = [
  "Akuressa",
  "Ambalangoda",
  "Ambalantota",
  "Ampara",
  "Anamaduwa",
  "Angoda",
  "Anuradhapura",
  "Aralaganwila",
  "Attanagalla",
  "Avissawella",
  "Badulla",
  "Balangoda",
  "Bandarawela",
  "Battaramulla",
  "Batticaloa",
  "Beliatta",
  "Beruwala",
  "Boralesgamuwa",
  "Chavakachcheri",
  "Chilaw",
  "Colombo",
  "Colombo Fort",
  "Dambulla",
  "Dankotuwa",
  "Dehiwala",
  "Delgoda",
  "Deraniyagala",
  "Devinuwara",
  "Dharga Town",
  "Digana",
  "Divulapitiya",
  "Eheliyagoda",
  "Elpitiya",
  "Embilipitiya",
  "Galle",
  "Gampaha",
  "Gampola",
  "Godakawela",
  "Hambantota",
  "Hanwella",
  "Haputale",
  "Hatton",
  "Hikkaduwa",
  "Homagama",
  "Horana",
  "Ingiriya",
  "Ja-Ela",
  "Jaffna",
  "Kadawatha",
  "Kalmunai",
  "Kalutara",
  "Kandy",
  "Kantale",
  "Karapitiya",
  "Kattankudy",
  "Kegalle",
  "Kelaniya",
  "Kilinochchi",
  "Kiribathgoda",
  "Kochchikade",
  "Kotikawatta",
  "Kuliyapitiya",
  "Kurunegala",
  "Maharagama",
  "Mahiyanganaya",
  "Mannar",
  "Marawila",
  "Matale",
  "Matara",
  "Medawachchiya",
  "Minuwangoda",
  "Monaragala",
  "Moratuwa",
  "Mullaitivu",
  "Nawala",
  "Nawalapitiya",
  "Negombo",
  "Nelliady",
  "Nittambuwa",
  "Nuwara Eliya",
  "Pannala",
  "Panadura",
  "Peliyagoda",
  "Pilimathalawa",
  "Pitigala",
  "Point Pedro",
  "Polgahawela",
  "Polonnaruwa",
  "Puttalam",
  "Ragama",
  "Rambukkana",
  "Ratnapura",
  "Tangalle",
  "Thalawathugoda",
  "Thambuttegama",
  "Trincomalee",
  "Udugampola",
  "Vavuniya",
  "Warakapola",
  "Wattala",
  "Welimada",
  "Welisara",
  "Wennappuwa",
];

export const BANK_BRANCH_OPTIONS = {
  "Bank of Ceylon": SRI_LANKA_BRANCH_CITIES,
  "People's Bank": SRI_LANKA_BRANCH_CITIES,
  "Commercial Bank": SRI_LANKA_BRANCH_CITIES,
  "Sampath Bank": SRI_LANKA_BRANCH_CITIES,
  "Hatton National Bank": SRI_LANKA_BRANCH_CITIES,
  "DFCC Bank": SRI_LANKA_BRANCH_CITIES,
  "NDB Bank": SRI_LANKA_BRANCH_CITIES,
  "Seylan Bank": SRI_LANKA_BRANCH_CITIES,
};

export const BANK_OPTIONS = Object.keys(BANK_BRANCH_OPTIONS);

export const getBranchOptions = (bankName) => BANK_BRANCH_OPTIONS[bankName] || [];

export const ALL_BRANCH_OPTIONS = [...SRI_LANKA_BRANCH_CITIES].sort((a, b) =>
  a.localeCompare(b)
);